C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/5,4/
      DATA (SPROP(I,-1,1),I=1,2)/25,25/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/6,-1/
      DATA (SPROP(I,-2,1),I=1,2)/66,66/
      DATA TPRID(-2,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/-2,3/
      DATA (SPROP(I,-3,1),I=1,2)/-24,-24/
      DATA TPRID(-3,1)/0/
C     Diagram 2
      DATA MAPCONFIG(2)/2/
      DATA (IFOREST(I,-1,2),I=1,2)/5,4/
      DATA (SPROP(I,-1,2),I=1,2)/23,23/
      DATA TPRID(-1,2)/0/
      DATA (IFOREST(I,-2,2),I=1,2)/6,-1/
      DATA (SPROP(I,-2,2),I=1,2)/66,66/
      DATA TPRID(-2,2)/0/
      DATA (IFOREST(I,-3,2),I=1,2)/-2,3/
      DATA (SPROP(I,-3,2),I=1,2)/-24,-24/
      DATA TPRID(-3,2)/0/
C     Diagram 3
      DATA MAPCONFIG(3)/3/
      DATA (IFOREST(I,-1,3),I=1,2)/6,5/
      DATA (SPROP(I,-1,3),I=1,2)/24,0/
      DATA TPRID(-1,3)/0/
      DATA (IFOREST(I,-2,3),I=1,2)/-1,4/
      DATA (SPROP(I,-2,3),I=1,2)/66,0/
      DATA TPRID(-2,3)/0/
      DATA (IFOREST(I,-3,3),I=1,2)/-2,3/
      DATA (SPROP(I,-3,3),I=1,2)/-24,0/
      DATA TPRID(-3,3)/0/
C     Diagram 4
      DATA MAPCONFIG(4)/4/
      DATA (IFOREST(I,-1,4),I=1,2)/6,4/
      DATA (SPROP(I,-1,4),I=1,2)/0,-24/
      DATA TPRID(-1,4)/0/
      DATA (IFOREST(I,-2,4),I=1,2)/5,-1/
      DATA (SPROP(I,-2,4),I=1,2)/0,66/
      DATA TPRID(-2,4)/0/
      DATA (IFOREST(I,-3,4),I=1,2)/-2,3/
      DATA (SPROP(I,-3,4),I=1,2)/0,-24/
      DATA TPRID(-3,4)/0/
C     Number of configs
      DATA MAPCONFIG(0)/4/
