ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM_RHN_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_15 = ', GC_15
      WRITE(*,2) 'GC_17 = ', GC_17
      WRITE(*,2) 'GC_18 = ', GC_18
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_27 = ', GC_27
      WRITE(*,2) 'GC_35 = ', GC_35
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_49 = ', GC_49
      WRITE(*,2) 'GC_54 = ', GC_54
      WRITE(*,2) 'GC_55 = ', GC_55
      WRITE(*,2) 'GC_57 = ', GC_57
      WRITE(*,2) 'GC_58 = ', GC_58
