ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MS,MDL_MU,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA
     $ ,MDL_MC,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MMU,MDL_MNR

      COMMON/MASSES/ MDL_MS,MDL_MU,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MC
     $ ,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MMU,MDL_MNR


      DOUBLE PRECISION MDL_WW,MDL_WT,MDL_WZ,MDL_WC,MDL_WB,MDL_WNR
     $ ,MDL_WH

      COMMON/WIDTHS/ MDL_WW,MDL_WT,MDL_WZ,MDL_WC,MDL_WB,MDL_WNR,MDL_WH


      DOUBLE COMPLEX GC_13, GC_14, GC_15, GC_17, GC_18, GC_23, GC_27,
     $  GC_35, GC_36, GC_40, GC_49, GC_54, GC_55, GC_57, GC_58

      COMMON/COUPLINGS/ GC_13, GC_14, GC_15, GC_17, GC_18, GC_23,
     $  GC_27, GC_35, GC_36, GC_40, GC_49, GC_54, GC_55, GC_57, GC_58

